#!/usr/bin/env mksh
#
# === {{CMD}}
# === {{CMD}} dev|spec

PATH="$PATH:$THIS_DIR/../sh_color/bin"
PATH="$PATH:$THIS_DIR/../my_crystal/bin"

if [[ -z "$@" ]]; then
  local +x ACTION="dev"
else
  local +x ACTION="$1"; shift
fi

case "$ACTION" in

  dev)
    CMD="mu-html watch run-dev"
    $CMD || :
    mksh_setup watch "-r src -r specs -r bin" "$CMD"
    ;;

  run-dev)
    echo "=== Compiling..." >&2
    mkdir -p tmp
    my_crystal build specs/specs.cr -o tmp/specs
    echo "=== Running... $(date "+%H:%M:%S") ..." >&2
    tmp/specs
    ;;

  spec)
    local +x CMD="mu-html spec run"

    $CMD || :
    mksh_setup watch "-r src -r spec -r bin -r sh" "$CMD"
    ;;

  *)
    echo "!!! Invalid option: $ACTION $@" >&2
    exit 2
    ;;

esac




